---
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: goapp
  namespace: default
spec:
  revisionTemplate:
    spec:
      containerConcurrency: 2
      allowAsync: "true"
      container:
        image: nimak/knative-sample-app:v3
        imagePullPolicy: Always
        env:
          - name: NAME
            value: "Nima"
